#! /bin/bash

git push origin master

git subtree push --prefix=android-form/ formorigin master
git subtree push --prefix=android-adapter/ adapterorigin master
git subtree push --prefix=android-views/ vieworigin master
git subtree push --prefix=android-grids/ gridorigin master
git subtree push --prefix=android-pagination/ paginationorigin master
