#! /bin/bash

git push origin master

git subtree push --prefix=form/ git@github.com:eddmash/android-form.git master
git subtree push --prefix=adapter/ git@github.com:eddmash/filterableadapter.git master
git subtree push --prefix=views/ git@github.com:eddmash/android-views.git master
git subtree push --prefix=grid/ git@github.com:eddmash/android-grids.git master
git subtree push --prefix=pagination/ git@github.com:eddmash/pagination.git master
git subtree push --prefix=validation/ git@github.com:eddmash/validation.git master
git subtree push --prefix=dialogs/ git@github.com:eddmash/dialogs.git master
